# -*- coding: utf-8 -*-
testString="""
Air pollution harms human health and the environment. In Europe, emissions of many air pollutants have decreased substantially over the past decades, resulting in improved air quality across the region. However, air pollutant concentrations are still too high, and air quality problems persist. A significant proportion of Europe's population live in areas, especially cities, where exceedances of air quality standards occur: ozone, nitrogen dioxide and particulate matter (PM) pollution pose serious health risks. Several countries have exceeded one or more of their 2010 emission limits for four important air pollutants. Reducing air pollution therefore remains important.
Air pollution is a local, pan-European and hemispheric issue. Air pollutants released in one country may be transported in the atmosphere, contributing to or resulting in poor air quality elsewhere.

Particulate matter, nitrogen dioxide and ground-level ozone, are now generally recognised as the three pollutants that most significantly affect human health. Long-term and peak exposures to these pollutants range in severity of impact, from impairing the respiratory system to premature death. Around 90 % of city dwellers in Europe are exposed to pollutants at concentrations higher than the air quality levels deemed harmful to health. For example, fine particulate matter (PM2.5) in air has been estimated to reduce life expectancy in the EU by more than eight months. Benzo(a)pyrene is a carcinogenic pollutant of increasing concern, with concentrations being above the threshold set to protect human health in several urban areas, especially in central and eastern Europe.

Air pollution is causing damage to human health and ecosystems. Large parts of the population do not live in a healthy environment, according to current standards. To get on to a sustainable path, Europe will have to be ambitious and go beyond current legislation.

Hans Bruyninckx, EEA Executive Director

 Air pollution also damages our environment.

Acidification was substantially reduced between 1990 and 2010 in Europe’s sensitive ecosystem areas that were subjected to acid deposition of excess sulphur and nitrogen compounds.
Eutrophication, an environmental problem caused by the input of excessive nutrients into ecosystems, saw less progress. The area of sensitive ecosystems affected by excessive atmospheric nitrogen diminished only slightly between 1990 and 2010.
Crop damage is caused by exposure to high ozone concentrations. Most agricultural crops are exposed to ozone levels that exceed the EU long-term objective intended to protect vegetation. This notably includes a significant proportion of agricultural areas, particularly in southern, central and eastern Europe.
 

Europe’s air quality has not always improved in line with the general decrease of anthropogenic (human-caused) emissions of air pollutants. Reasons for this are complex:

there is not always a clear linear relationship between decreasing emissions and the concentrations of air pollutants observed in the air;
there is a growing contribution of long-distance transport of air pollutants to Europe from other countries in the northern hemisphere.
Targeted efforts to reduce emissions are therefore still required to further protect human health and the environment in Europe.

Sources of air pollution

There are various sources of air pollution, both anthropogenic and of natural origin:

burning of fossil fuels in electricity generation, transport, industry and households;
industrial processes and solvent use, for example in chemical and mineral industries;
agriculture; 
waste treatment;
volcanic eruptions, windblown dust, sea-salt spray and emissions of volatile organic compounds from plants are examples of natural emission sources.
European Union policies

The EU’s long-term objective is to achieve levels of air quality that do not result in unacceptable impacts on, and risks to, human health and the environment. The EU acts at many levels to reduce exposure to air pollution: through legislation; cooperation with sectors responsible for air pollution, as well as international, national and regional authorities and non-governmental organisations; and research. EU policies aim to reduce exposure to air pollution by reducing emissions and setting limits and target values for air quality. In late 2013, the European Commission adopted a proposed Clean Air Quality Package including new measures to reduce air pollution.

Find out more about European air pollution policies

EEA activities

The European Environment Agency (EEA) is the European Union's air pollution data centre; it supports the implementation of EU legislation linked to air emissions and air quality. The EEA also contributes to the evaluation of EU air pollution policies and to the development of long-term strategies to improve air quality in Europe.

EEA’s work focuses on:

making a range of air pollution data publicly available,
documenting and assessing air pollution trends and related policies and measures in Europe, and
investigating the trade-offs and synergies between air pollution and policies in different areas, including climate change, energy, transport and industry. 
"""

sortingTest={   u'http://dbpedia.org/resource/Abiogenesis': {   'confidence': 0.7243,
                                                    'count': 1,
                                                    'label': u'Abiogenesis',
                                                    'spots': [u'origin']},
    u'http://dbpedia.org/resource/Acid_rain': {   'confidence': 0.8531,
                                                  'count': 1,
                                                  'label': u'Acid rain',
                                                  'spots': [   u'acid deposition']},
    u'http://dbpedia.org/resource/Aeolian_processes': {   'confidence': 0.7031,
                                                          'count': 1,
                                                          'label': u'Aeolian',
                                                          'spots': [   u'windblown']},
    u'http://dbpedia.org/resource/Agriculture': {   'confidence': 0.7331,
                                                    'count': 2,
                                                    'label': u'Agriculture',
                                                    'spots': [   u'agricultural',
                                                                 u'agriculture']},
    u'http://dbpedia.org/resource/Air_pollutant_concentrations': {   'confidence': 0.8202,
                                                                     'count': 1,
                                                                     'label': u'Air pollutant concentrations',
                                                                     'spots': [   u'air pollutant concentrations']},
    u'http://dbpedia.org/resource/Air_pollution': {   'confidence': 0.856,
                                                      'count': 44,
                                                      'label': u'Air pollution',
                                                      'spots': [   u'air pollution',
                                                                   u'emissions',
                                                                   u'air pollutants',
                                                                   u'air quality',
                                                                   u'emission',
                                                                   u'clean air',
                                                                   u'air emissions']},
    u'http://dbpedia.org/resource/Atmosphere': {   'confidence': 0.7432,
                                                   'count': 2,
                                                   'label': u'Atmosphere',
                                                   'spots': [   u'atmosphere',
                                                                u'atmospheric']},
    u'http://dbpedia.org/resource/Atmosphere_of_Earth': {   'confidence': 0.6415,
                                                            'count': 1,
                                                            'label': u'Air',
                                                            'spots': [u'air']},
    u'http://dbpedia.org/resource/Authority': {   'confidence': 0.6883,
                                                  'count': 1,
                                                  'label': u'Authority',
                                                  'spots': [u'authorities']},
    u'http://dbpedia.org/resource/Benzodiazepine': {   'confidence': 0.6693,
                                                       'count': 1,
                                                       'label': u'Benzodiazepine',
                                                       'spots': [u'benzo']},
    u'http://dbpedia.org/resource/Carcinogen': {   'confidence': 0.7678,
                                                   'count': 1,
                                                   'label': u'Carcinogen',
                                                   'spots': [u'carcinogenic']},
    u'http://dbpedia.org/resource/Central_Europe': {   'confidence': 0.7264,
                                                       'count': 2,
                                                       'label': u'Central Europe',
                                                       'spots': [   u'central and eastern europe']},
    u'http://dbpedia.org/resource/Chemical_process': {   'confidence': 0.6681,
                                                         'count': 1,
                                                         'label': u'Chemical process',
                                                         'spots': [   u'processes']},
    u'http://dbpedia.org/resource/Chemical_substance': {   'confidence': 0.7334,
                                                           'count': 1,
                                                           'label': u'Chemical',
                                                           'spots': [   u'chemical']},
    u'http://dbpedia.org/resource/Climate_change': {   'confidence': 0.8096,
                                                       'count': 1,
                                                       'label': u'Climate change',
                                                       'spots': [   u'climate change']},
    u'http://dbpedia.org/resource/Concentration': {   'confidence': 0.6891,
                                                      'count': 4,
                                                      'label': u'Concentration',
                                                      'spots': [   u'concentrations',
                                                                   u'proportion']},
    u'http://dbpedia.org/resource/Cooperation': {   'confidence': 0.648,
                                                    'count': 1,
                                                    'label': u'Cooperation',
                                                    'spots': [u'cooperation']},
    u'http://dbpedia.org/resource/Data': {   'confidence': 0.6888,
                                             'count': 1,
                                             'label': u'Data',
                                             'spots': [u'data']},
    u'http://dbpedia.org/resource/Data_center': {   'confidence': 0.6718,
                                                    'count': 1,
                                                    'label': u'Data center',
                                                    'spots': [u'data centre']},
    u'http://dbpedia.org/resource/Dust': {   'confidence': 0.7466,
                                             'count': 1,
                                             'label': u'Dust',
                                             'spots': [u'dust']},
    u'http://dbpedia.org/resource/Economic_development': {   'confidence': 0.7215,
                                                             'count': 1,
                                                             'label': u'Economic development',
                                                             'spots': [   u'development']},
    u'http://dbpedia.org/resource/Ecosystem': {   'confidence': 0.8067,
                                                  'count': 4,
                                                  'label': u'Ecosystem',
                                                  'spots': [   u'ecosystems',
                                                               u'ecosystem']},
    u'http://dbpedia.org/resource/Electricity_generation': {   'confidence': 0.763,
                                                               'count': 1,
                                                               'label': u'Electricity generation',
                                                               'spots': [   u'electricity generation']},
    u'http://dbpedia.org/resource/Employment': {   'confidence': 0.6633,
                                                   'count': 1,
                                                   'label': u'Employment',
                                                   'spots': [u'work']},
    u'http://dbpedia.org/resource/Energy': {   'confidence': 0.7363,
                                               'count': 1,
                                               'label': u'Energy',
                                               'spots': [u'energy']},
    u'http://dbpedia.org/resource/Environmental_issue': {   'confidence': 0.7148,
                                                            'count': 1,
                                                            'label': u'Environmental issue',
                                                            'spots': [   u'environmental problem']},
    u'http://dbpedia.org/resource/Environmental_protection': {   'confidence': 0.676,
                                                                 'count': 1,
                                                                 'label': u'Environmental protection',
                                                                 'spots': [   u'healthy environment']},
    u'http://dbpedia.org/resource/Europe': {   'confidence': 0.7225,
                                               'count': 8,
                                               'label': u'Europe',
                                               'spots': [u'europe']},
    u'http://dbpedia.org/resource/European_Commission': {   'confidence': 0.8631,
                                                            'count': 1,
                                                            'label': u'European Commission',
                                                            'spots': [   u'european commission']},
    u'http://dbpedia.org/resource/European_Environment_Agency': {   'confidence': 0.9442,
                                                                    'count': 6,
                                                                    'label': u'European Environment Agency',
                                                                    'spots': [   u'eea',
                                                                                 u'european environment agency']},
    u'http://dbpedia.org/resource/European_Union': {   'confidence': 0.8683,
                                                       'count': 6,
                                                       'label': u'European Union',
                                                       'spots': [   u'eu',
                                                                    u'european union']},
    u'http://dbpedia.org/resource/Eutrophication': {   'confidence': 0.9035,
                                                       'count': 1,
                                                       'label': u'Eutrophication',
                                                       'spots': [   u'eutrophication']},
    u'http://dbpedia.org/resource/Fire': {   'confidence': 0.6794,
                                             'count': 1,
                                             'label': u'Fire',
                                             'spots': [u'damage']},
    u'http://dbpedia.org/resource/Flora': {   'confidence': 0.6913,
                                              'count': 1,
                                              'label': u'Flora',
                                              'spots': [u'plants']},
    u'http://dbpedia.org/resource/Hans_Bruyninckx': {   'confidence': 0.8767,
                                                        'count': 1,
                                                        'label': u'Hans Bruyninckx',
                                                        'spots': [   u'hans bruyninckx']},
    u'http://dbpedia.org/resource/Health': {   'confidence': 0.7422,
                                               'count': 7,
                                               'label': u'Health',
                                               'spots': [   u'human health',
                                                            u'health']},
    u'http://dbpedia.org/resource/Household': {   'confidence': 0.6606,
                                                  'count': 1,
                                                  'label': u'Household',
                                                  'spots': [u'households']},
    u'http://dbpedia.org/resource/Human': {   'confidence': 0.6457,
                                              'count': 1,
                                              'label': u'Human',
                                              'spots': [u'human']},
    u'http://dbpedia.org/resource/Human_impact_on_the_environment': {   'confidence': 0.827,
                                                                        'count': 2,
                                                                        'label': u'Anthropogenic',
                                                                        'spots': [   u'anthropogenic']},
    u'http://dbpedia.org/resource/Hypothermia': {   'confidence': 0.6479,
                                                    'count': 1,
                                                    'label': u'Hypothermia',
                                                    'spots': [u'exposure']},
    u'http://dbpedia.org/resource/Implementation': {   'confidence': 0.6766,
                                                       'count': 1,
                                                       'label': u'Implementation',
                                                       'spots': [   u'implementation']},
    u'http://dbpedia.org/resource/Industry': {   'confidence': 0.7379,
                                                 'count': 2,
                                                 'label': u'Industry',
                                                 'spots': [   u'industrial',
                                                              u'industry']},
    u'http://dbpedia.org/resource/Kingdom_of_the_Netherlands': {   'confidence': 0.6591,
                                                                   'count': 1,
                                                                   'label': u'Kingdom of the Netherlands',
                                                                   'spots': [   u'countries']},
    u'http://dbpedia.org/resource/Legislation': {   'confidence': 0.6723,
                                                    'count': 1,
                                                    'label': u'Legislation',
                                                    'spots': [u'legislation']},
    u'http://dbpedia.org/resource/Life_expectancy': {   'confidence': 0.7444,
                                                        'count': 1,
                                                        'label': u'Life expectancy',
                                                        'spots': [   u'life expectancy']},
    u'http://dbpedia.org/resource/Linearity': {   'confidence': 0.901,
                                                  'count': 1,
                                                  'label': u'Linear',
                                                  'spots': [u'linear']},
    u'http://dbpedia.org/resource/Measurement': {   'confidence': 0.6499,
                                                    'count': 1,
                                                    'label': u'Measurement',
                                                    'spots': [u'measures']},
    u'http://dbpedia.org/resource/Medieval_demography': {   'confidence': 0.6824,
                                                            'count': 1,
                                                            'label': u'Medieval demography',
                                                            'spots': [   u"europe's population"]},
    u'http://dbpedia.org/resource/Mining': {   'confidence': 0.7217,
                                               'count': 1,
                                               'label': u'Mining',
                                               'spots': [   u'mineral industries']},
    u'http://dbpedia.org/resource/Nation': {   'confidence': 0.7086,
                                               'count': 1,
                                               'label': u'Nation',
                                               'spots': [u'national']},
    u'http://dbpedia.org/resource/Natural_environment': {   'confidence': 0.7492,
                                                            'count': 4,
                                                            'label': u'Environment',
                                                            'spots': [   u'environment']},
    u'http://dbpedia.org/resource/Nature': {   'confidence': 0.7462,
                                               'count': 2,
                                               'label': u'Nature',
                                               'spots': [u'natural']},
    u'http://dbpedia.org/resource/Nitrogen': {   'confidence': 0.8062,
                                                 'count': 2,
                                                 'label': u'Nitrogen',
                                                 'spots': [u'nitrogen']},
    u'http://dbpedia.org/resource/Nitrogen_dioxide': {   'confidence': 0.9078,
                                                         'count': 2,
                                                         'label': u'Nitrogen dioxide',
                                                         'spots': [   u'nitrogen dioxide']},
    u'http://dbpedia.org/resource/Non-governmental_organization': {   'confidence': 0.7393,
                                                                      'count': 1,
                                                                      'label': u'Non-governmental organization',
                                                                      'spots': [   u'non-governmental organisations']},
    u'http://dbpedia.org/resource/Northern_Hemisphere': {   'confidence': 0.805,
                                                            'count': 1,
                                                            'label': u'Northern Hemisphere',
                                                            'spots': [   u'northern hemisphere']},
    u'http://dbpedia.org/resource/Nutrient': {   'confidence': 0.715,
                                                 'count': 1,
                                                 'label': u'Nutrient',
                                                 'spots': [u'nutrients']},
    u'http://dbpedia.org/resource/Objectivity_%28philosophy%29': {   'confidence': 0.641,
                                                                     'count': 1,
                                                                     'label': u'Objective',
                                                                     'spots': [   u'objective']},
    u'http://dbpedia.org/resource/Ocean_acidification': {   'confidence': 0.7419,
                                                            'count': 1,
                                                            'label': u'Ocean acidification',
                                                            'spots': [   u'acidification']},
    u'http://dbpedia.org/resource/Ozone': {   'confidence': 0.8119,
                                              'count': 3,
                                              'label': u'Ozone',
                                              'spots': [u'ozone']},
    u'http://dbpedia.org/resource/Particulates': {   'confidence': 0.8395,
                                                     'count': 4,
                                                     'label': u'Particulate matter',
                                                     'spots': [   u'particulate matter',
                                                                  u'pm',
                                                                  u'fine particulate matter']},
    u'http://dbpedia.org/resource/Policy': {   'confidence': 0.7267,
                                               'count': 6,
                                               'label': u'Policy',
                                               'spots': [u'policies']},
    u'http://dbpedia.org/resource/Pollutant': {   'confidence': 0.7563,
                                                  'count': 2,
                                                  'label': u'Pollutant',
                                                  'spots': [   u'pollutants',
                                                               u'pollutant']},
    u'http://dbpedia.org/resource/Pollution': {   'confidence': 0.7726,
                                                  'count': 3,
                                                  'label': u'Pollution',
                                                  'spots': [   u'pollution',
                                                               u'pollutants']},
    u'http://dbpedia.org/resource/Poverty': {   'confidence': 0.6672,
                                                'count': 1,
                                                'label': u'Poverty',
                                                'spots': [u'poor']},
    u'http://dbpedia.org/resource/Publicity': {   'confidence': 0.62,
                                                  'count': 1,
                                                  'label': u'Publicity',
                                                  'spots': [u'exposure']},
    u'http://dbpedia.org/resource/Pyrene': {   'confidence': 0.8352,
                                               'count': 1,
                                               'label': u'Pyrene',
                                               'spots': [u'pyrene']},
    u'http://dbpedia.org/resource/Rangeland': {   'confidence': 0.6392,
                                                  'count': 1,
                                                  'label': u'Rangeland',
                                                  'spots': [u'range']},
    u'http://dbpedia.org/resource/Regional_planning': {   'confidence': 0.6831,
                                                          'count': 1,
                                                          'label': u'Regional planning',
                                                          'spots': [   u'regional']},
    u'http://dbpedia.org/resource/Research': {   'confidence': 0.6837,
                                                 'count': 1,
                                                 'label': u'Research',
                                                 'spots': [u'research']},
    u'http://dbpedia.org/resource/Respiratory_system': {   'confidence': 0.7981,
                                                           'count': 1,
                                                           'label': u'Respiratory system',
                                                           'spots': [   u'respiratory system']},
    u'http://dbpedia.org/resource/Risk': {   'confidence': 0.7165,
                                             'count': 1,
                                             'label': u'Risk',
                                             'spots': [u'risks']},
    u'http://dbpedia.org/resource/Sea_salt': {   'confidence': 0.7499,
                                                 'count': 1,
                                                 'label': u'Sea salt',
                                                 'spots': [u'sea-salt']},
    u'http://dbpedia.org/resource/Sea_spray': {   'confidence': 0.7363,
                                                  'count': 1,
                                                  'label': u'Sea spray',
                                                  'spots': [u'salt spray']},
    u'http://dbpedia.org/resource/Solvent': {   'confidence': 0.7815,
                                                'count': 1,
                                                'label': u'Solvent',
                                                'spots': [u'solvent']},
    u'http://dbpedia.org/resource/Southern_Europe': {   'confidence': 0.6699,
                                                        'count': 1,
                                                        'label': u'Southern Europe',
                                                        'spots': [   u'southern']},
    u'http://dbpedia.org/resource/Strategy': {   'confidence': 0.6492,
                                                 'count': 1,
                                                 'label': u'Strategy',
                                                 'spots': [u'strategies']},
    u'http://dbpedia.org/resource/Sulfur': {   'confidence': 0.7743,
                                               'count': 1,
                                               'label': u'Sulfur',
                                               'spots': [u'sulphur']},
    u'http://dbpedia.org/resource/Sustainability': {   'confidence': 0.7247,
                                                       'count': 1,
                                                       'label': u'Sustainability',
                                                       'spots': [   u'sustainable']},
    u'http://dbpedia.org/resource/Synergy': {   'confidence': 0.6857,
                                                'count': 1,
                                                'label': u'Synergy',
                                                'spots': [u'synergies']},
    u'http://dbpedia.org/resource/Term_%28time%29': {   'confidence': 0.651,
                                                        'count': 1,
                                                        'label': u'Long-term',
                                                        'spots': [   u'long-term']},
    u'http://dbpedia.org/resource/Trade': {   'confidence': 0.7102,
                                              'count': 1,
                                              'label': u'Trade',
                                              'spots': [u'trade']},
    u'http://dbpedia.org/resource/Transport': {   'confidence': 0.7224,
                                                  'count': 3,
                                                  'label': u'Transport',
                                                  'spots': [   u'transport',
                                                               u'transport, industry']},
    u'http://dbpedia.org/resource/Tropospheric_ozone': {   'confidence': 0.8288,
                                                           'count': 1,
                                                           'label': u'Ground-level ozone',
                                                           'spots': [   u'ground-level ozone']},
    u'http://dbpedia.org/resource/Value_%28ethics%29': {   'confidence': 0.7011,
                                                           'count': 1,
                                                           'label': u'Values',
                                                           'spots': [   u'values']},
    u'http://dbpedia.org/resource/Vegetation': {   'confidence': 0.6969,
                                                   'count': 1,
                                                   'label': u'Vegetation',
                                                   'spots': [u'vegetation']},
    u'http://dbpedia.org/resource/Volatile_organic_compound': {   'confidence': 0.8206,
                                                                  'count': 1,
                                                                  'label': u'Volatile organic compound',
                                                                  'spots': [   u'volatile organic compounds']},
    u'http://dbpedia.org/resource/Volcano': {   'confidence': 0.7211,
                                                'count': 1,
                                                'label': u'Volcano',
                                                'spots': [   u'volcanic eruptions']},
    u'http://dbpedia.org/resource/Waste_treatment': {   'confidence': 0.6925,
                                                        'count': 1,
                                                        'label': u'Waste treatment',
                                                        'spots': [   u'waste treatment']},
    u'http://dbpedia.org/resource/World_population': {   'confidence': 0.7084,
                                                         'count': 1,
                                                         'label': u'World population',
                                                         'spots': [   u'population']}}

print len(sortingTest)     
print sorted(sortingTest, key=lambda x:(sortingTest[x]['count'],sortingTest[x]['confidence']), reverse=True)                                                    
